# Generated by Django 5.0.6 on 2026-06-08 16:39

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.CharField(default=tasks.models._uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('local_change_date', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.CharField(default=tasks.models._uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('local_change_date', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('PRIVATE', 'Личная'), ('CORPORATE', 'Корпоративная')], default='PRIVATE', max_length=12)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('start_period', models.DateField(blank=True, null=True)),
                ('end_period', models.DateField(blank=True, null=True)),
                ('shared', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=tasks.models._uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('local_change_date', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('note', models.TextField(blank=True)),
                ('task_type', models.IntegerField(choices=[(0, 'Не задан'), (1, 'Входящие'), (2, 'Сегодня'), (3, 'Неделя'), (4, 'Позже')], default=1)),
                ('state', models.IntegerField(choices=[(0, 'Активна'), (1, 'Скрыта')], default=0)),
                ('priority', models.FloatField(default=0.0)),
                ('done', models.BooleanField(default=False)),
                ('is_project', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('hide_until_date', models.DateTimeField(blank=True, null=True)),
                ('recur_rule', models.CharField(blank=True, max_length=255)),
                ('recur_parent_id', models.CharField(blank=True, max_length=32)),
                ('recur_exclude_dates', models.TextField(blank=True)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.context')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.goal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task')),
            ],
            options={
                'ordering': ['priority', '-created'],
            },
        ),
        migrations.CreateModel(
            name='CheckListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('done', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='tasks.task')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
