# Generated by Django 5.0.6 on 2026-06-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'В работе'), ('PAUSED', 'На паузе'), ('ACHIEVED', 'Достигнута'), ('DROPPED', 'Отменена')], default='ACTIVE', max_length=40),
        ),
    ]
