# Generated by Django 5.0.6 on 2026-06-08 19:44

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_goal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalTemplate',
            fields=[
                ('id', models.CharField(default=tasks.models._uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('local_change_date', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('PRIVATE', 'Личная'), ('CORPORATE', 'Корпоративная')], default='PRIVATE', max_length=12)),
                ('published', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tasks.goaltemplate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('SIMPLE', 'Простой'), ('SUM_RESULT', 'Сумма'), ('LAST_RESULT', 'Последнее')], default='SIMPLE', max_length=12)),
                ('planned', models.FloatField(default=0.0)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='tasks.milestonetemplate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('offset_days', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='tasks.milestonetemplate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='tasks.goaltemplate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
