# Generated by Django 5.0.6 on 2026-06-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_goaltemplate_milestonetemplate_keyresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
