# Generated by Django 5.0.6 on 2026-06-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_goal_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='from_template',
            field=models.BooleanField(default=False),
        ),
    ]
